import{a as p,S as v,i}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const q="54613743-5c52f100f8c0e070db7d9ab0d",R="https://pixabay.com/api/",E=15;p.defaults.baseURL=R;async function y(r,t){return(await p.get("",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:E}})).data}const b=document.querySelector(".gallery"),a=document.querySelector(".loader"),s=document.querySelector(".load-more"),A=new v(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const t=r.map(({webformatURL:l,largeImageURL:d,tags:e,likes:o,views:c,comments:P,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${d}">
          <img class="gallery-image" src="${l}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${c}</p>
          <p class="info-item"><b>Comments</b> ${P}</p>
          <p class="info-item"><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");b.insertAdjacentHTML("beforeend",t),A.refresh()}function O(){b.innerHTML=""}function w(){a==null||a.classList.remove("is-hidden")}function g(){a==null||a.classList.add("is-hidden")}function _(){s==null||s.classList.remove("is-hidden"),s&&(s.disabled=!1)}function h(){s==null||s.classList.add("is-hidden"),s&&(s.disabled=!0)}const $=document.querySelector(".form"),m=document.querySelector(".load-more"),x=document.querySelector(".gallery"),B=15;let u="",n=1,f=0;h();g();$.addEventListener("submit",C);m.addEventListener("click",M);async function C(r){if(r.preventDefault(),u=r.currentTarget.elements["search-text"].value.trim(),!u){i.warning({message:"Please enter a search query.",position:"topRight"});return}n=1,f=0,O(),h(),w();try{const t=await y(u,n);if(!t.hits||t.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(t.hits),f=Math.ceil(t.totalHits/B),n<f?_():(h(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{g()}}async function M(){n+=1,m.disabled=!0,w();try{const r=await y(u,n);L(r.hits),T(),n>=f?(h(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m.disabled=!1}catch{i.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{g()}}function T(){const r=x.firstElementChild;if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
