import{a as p,S as v,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&f(l)}).observe(document,{childList:!0,subtree:!0});function u(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(e){if(e.ep)return;e.ep=!0;const o=u(e);fetch(e.href,o)}})();const q="54613743-5c52f100f8c0e070db7d9ab0d",R="https://pixabay.com/api/",E=15;p.defaults.baseURL=R;async function y(r,t){return(await p.get("",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:E}})).data}const b=document.querySelector(".gallery"),n=document.querySelector(".loader"),s=document.querySelector(".load-more"),A=new v(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const t=r.map(({webformatURL:u,largeImageURL:f,tags:e,likes:o,views:l,comments:P,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${f}">
          <img class="gallery-image" src="${u}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${l}</p>
          <p class="info-item"><b>Comments</b> ${P}</p>
          <p class="info-item"><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");b.insertAdjacentHTML("beforeend",t),A.refresh()}function O(){b.innerHTML=""}function w(){n==null||n.classList.remove("is-hidden")}function g(){n==null||n.classList.add("is-hidden")}function m(){s==null||s.classList.remove("is-hidden"),s&&(s.disabled=!1)}function c(){s==null||s.classList.add("is-hidden"),s&&(s.disabled=!0)}const _=document.querySelector(".form"),$=document.querySelector(".load-more"),x=document.querySelector(".gallery"),B=15;let h="",i=1,d=0;c();g();_.addEventListener("submit",C);$.addEventListener("click",M);async function C(r){if(r.preventDefault(),h=r.currentTarget.elements["search-text"].value.trim(),!h){a.warning({message:"Please enter a search query.",position:"topRight"});return}i=1,d=0,O(),c(),w();try{const t=await y(h,i);if(!t.hits||t.hits.length===0){a.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(t.hits),d=Math.ceil(t.totalHits/B),i<d?m():(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{g()}}async function M(){i+=1,c(),w();try{const r=await y(h,i);L(r.hits),T(),i>=d?(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m()}catch{i-=1,a.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),i<d?m():c()}finally{g()}}function T(){const r=x.firstElementChild;if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
